# Generated by Django 4.0 on 2022-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='balance',
            field=models.BigIntegerField(),
        ),
    ]
